Cifrado cesar Jessica Manturano
Laboratoria-learning/caesar-cipher pull request #54
Opened 2017-11-07 17:51 UTC by JessicaMP

Hola, muchas gracias por revisar mi codigo.

2017-11-10 17:06 UTC, RuthSalvador commented
@developerVilchez `eslint` OK

2017-11-21 23:22 UTC, chuga requested changes
Buen trabajo! Algunos detalles que debemos mejorar:

2017-11-21 23:22 UTC, chuga commented on js/app.js
> +      output += String.fromCharCode((input1.charCodeAt(k) - 65 + 33) % 26 + 65);
`k` no existe en este contexto, debiese ser `i`

2017-11-21 23:22 UTC, chuga commented on js/app.js
> +  var num = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9);
Para crear un array debes hacerlo con`[]`. En este caso esto debiese ser `var numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];'.

2017-11-21 23:22 UTC, chuga commented on js/app.js
> +// Creamos una variable input que almacene los datos que ingresan por medio de prompt
El comentario debe estar alineado con el código que comenta (faltan dos espacios).
También recuerda que los comentarios son útiles solo cuando el código en sí no es fácil de entender. En este caso la línea de código es bastante simple, por lo que un comentario no es necesario para poder entenderla.

2017-11-21 23:22 UTC, chuga commented on js/app.js
> +      while (input[j] === num) {
Lamentablemente este `while` no hace lo que quieres que haga ya que no se pueden comparar un caracter con un array de esta manera. Para ver si un array contiene un valor, puedes usar `numbers.include(input[j])`.
Ahora, cuando encuentras un número y pides otro input, necesitas volver a correr todo el for() de la línea 11, no solo seguir comparando desde la posición `j`, ya que el valor de input ha cambiado.

2017-11-21 23:22 UTC, chuga commented on js/app.js
> +  var input1 = input.toUpperCase();
Se te ocurre como poder soportar minúsculas también?

2017-11-21 23:22 UTC, chuga commented on js/app.js
> +      // de lo contrario se lee normal y se le agrega a la variable output el valor cifrado utilizando los dos metodos de ASCII input1.charCodeAt(k) te brinda la posicion de la letra en el codigo ASC
Cuando los comentarios son tan largos debes escribirlos de la siguiente manera: https://eslint.org/docs/developer-guide/code-conventions#multi-line-comments
```
/*
 * Linea 1
 * Linea 2
 */
```

2017-11-21 23:22 UTC, chuga commented on js/app.js
> +// Creamos la funcion de decifrado
Recuerda dejar una línea en blanco entre funciones, hace que tu código sea más fácil de leer :)

2023-01-23 00:45 UTC, closed without merging